# Generated by Django 5.2.4 on 2025-08-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField(blank=True)),
                ("api_key", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("batch_size", models.PositiveIntegerField(default=100)),
                ("num_workers", models.PositiveIntegerField(default=4)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("processed_items", models.PositiveIntegerField(default=0)),
                ("failed_items", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result_summary", models.JSONField(default=dict)),
                ("error_log", models.TextField(blank=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="processor.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=100)),
                ("data", models.JSONField()),
                ("is_processed", models.BooleanField(default=False)),
                ("is_failed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("processed_data", models.JSONField(blank=True, null=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="processor.processingjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("items_per_second", models.FloatField()),
                ("active_workers", models.PositiveIntegerField()),
                ("queue_size", models.PositiveIntegerField()),
                ("memory_usage_mb", models.FloatField(blank=True, null=True)),
                ("cpu_percent", models.FloatField(blank=True, null=True)),
                ("db_connections", models.PositiveIntegerField(blank=True, null=True)),
                ("db_query_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="processor.processingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "average_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "min_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "max_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("results_by_category", models.JSONField(default=dict)),
                ("total_processing_time", models.FloatField(default=0)),
                ("average_item_time", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="processor.processingjob",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["status", "-created_at"], name="processor_p_status_3d7f2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["data_source", "-created_at"],
                name="processor_p_data_so_1a5c01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataitem",
            index=models.Index(
                fields=["job", "is_processed"], name="processor_d_job_id_265154_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataitem",
            index=models.Index(
                fields=["job", "is_failed"], name="processor_d_job_id_4c7fe1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dataitem",
            unique_together={("job", "external_id")},
        ),
        migrations.AddIndex(
            model_name="processingmetrics",
            index=models.Index(
                fields=["job", "-timestamp"], name="processor_p_job_id_7d29b6_idx"
            ),
        ),
    ]
